// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxEfLe_bHjAji_cRm0zz2mEM5rnGhz1xM',
    appId: '1:53753495274:web:046a91eb63589efd23a193',
    messagingSenderId: '53753495274',
    projectId: 'attendancesheet-6c32f',
    authDomain: 'attendancesheet-6c32f.firebaseapp.com',
    storageBucket: 'attendancesheet-6c32f.firebasestorage.app',
    measurementId: 'G-EH22DWX3XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwA0XNBYQNlza32uFYiAFllGYYBz35u84',
    appId: '1:53753495274:android:132d9722801da1d723a193',
    messagingSenderId: '53753495274',
    projectId: 'attendancesheet-6c32f',
    storageBucket: 'attendancesheet-6c32f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxEfLe_bHjAji_cRm0zz2mEM5rnGhz1xM',
    appId: '1:53753495274:web:5513879a87b1fe1323a193',
    messagingSenderId: '53753495274',
    projectId: 'attendancesheet-6c32f',
    authDomain: 'attendancesheet-6c32f.firebaseapp.com',
    storageBucket: 'attendancesheet-6c32f.firebasestorage.app',
    measurementId: 'G-F213B0CZKW',
  );
}
